fieldLayouts:
  03c65a8d-d9a5-4dcc-b79c-b0bb97a266b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5f1119b9-f931-4684-a7be-f853e105d587
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d24e7970-4eb2-4b18-a014-945195478619
        userCondition: null
fs: drinks
handle: drinks
name: Drinks
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
