columnSuffix: pisdvyid
contentColumnType: 'decimal(12,2)'
fieldGroup: 0cd5513d-680b-4e2f-8a86-bda3ea67f79d # Drinks
handle: price
instructions: null
name: Price
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
